"""Añadir campos para control de códigos

Revision ID: 2316937aced4
Revises: ebe5a5a5b65f
Create Date: 2025-04-04 14:07:37.507879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2316937aced4'
down_revision = 'ebe5a5a5b65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('proceso', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('consecutivo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion_inicial', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion_inicial')
        batch_op.drop_column('version')
        batch_op.drop_column('consecutivo')
        batch_op.drop_column('proceso')
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###
