"""Agregar columna respuesta_correcta a preguntas_formacion

Revision ID: 25fc6384a117
Revises: c322018cc401
Create Date: 2025-04-05 19:03:50.856765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fc6384a117'
down_revision = 'c322018cc401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluaciones_capacitador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dominio_tema', sa.Integer(), nullable=True),
    sa.Column('claridad', sa.Integer(), nullable=True),
    sa.Column('material', sa.Integer(), nullable=True),
    sa.Column('tiempo', sa.Integer(), nullable=True),
    sa.Column('utilidad', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('asistente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asistente_id'], ['asistentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion_inicial')
        batch_op.drop_column('codigo_base')
        batch_op.drop_column('version')
        batch_op.drop_column('uso_consecutivo')

    with op.batch_alter_table('preguntas_formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuesta_correcta', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas_formacion', schema=None) as batch_op:
        batch_op.drop_column('respuesta_correcta')

    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uso_consecutivo', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('codigo_base', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion_inicial', sa.DATETIME(), nullable=True))

    op.drop_table('evaluaciones_capacitador')
    # ### end Alembic commands ###
