"""Añadir campos para profesional externo

Revision ID: 41ade267b897
Revises: ee16313492e8
Create Date: 2025-04-03 18:15:51.515487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ade267b897'
down_revision = 'ee16313492e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas_asistencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_externo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_externo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listas_asistencia', schema=None) as batch_op:
        batch_op.drop_column('email_externo')
        batch_op.drop_column('es_externo')

    # ### end Alembic commands ###
