"""Añadir campos de imágenes a FichaFormacion

Revision ID: 6c4c42f056e2
Revises: 25fc6384a117
Create Date: 2025-04-07 10:56:28.722860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4c42f056e2'
down_revision = '25fc6384a117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_personalizado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imagen_evento1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imagen_evento2', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.drop_column('imagen_evento2')
        batch_op.drop_column('imagen_evento1')
        batch_op.drop_column('logo_personalizado')

    # ### end Alembic commands ###
