"""Agregar campo tipo_documento a Asistente

Revision ID: bd060864e493
Revises: 6c4c42f056e2
Create Date: 2025-04-07 22:23:47.529777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd060864e493'
down_revision = '6c4c42f056e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistentes', schema=None) as batch_op:
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###
