"""empty message

Revision ID: c322018cc401
Revises: 2316937aced4
Create Date: 2025-04-04 17:13:31.416192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c322018cc401'
down_revision = '2316937aced4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_base', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('uso_consecutivo', sa.Integer(), nullable=True))
        batch_op.drop_column('proceso')
        batch_op.drop_column('consecutivo')
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('consecutivo', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('proceso', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('uso_consecutivo')
        batch_op.drop_column('codigo_base')

    # ### end Alembic commands ###
