"""Añadir campos metodologías y recursos

Revision ID: ebe5a5a5b65f
Revises: 41ade267b897
Create Date: 2025-04-03 20:00:57.597066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe5a5a5b65f'
down_revision = '41ade267b897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodologias', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recursos', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.drop_column('recursos')
        batch_op.drop_column('metodologias')

    # ### end Alembic commands ###
