"""Agregar campos de conclusiones e indicadores

Revision ID: feb085d2472c
Revises: bd060864e493
Create Date: 2025-04-08 20:24:09.084460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb085d2472c'
down_revision = 'bd060864e493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conclusiones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('indicadores', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichas_formacion', schema=None) as batch_op:
        batch_op.drop_column('indicadores')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('conclusiones')

    # ### end Alembic commands ###
